--- 
apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  labels:
    app: nginx
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared # 같은 external ip를 사용할 수 있다.
spec:
  # loadBalancerIP: 192.168.2.222
  ports: 
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector: 
    app: nginx
  type: LoadBalancer

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    app: nginx
spec: 
  selector: 
    matchLabels: 
      app: nginx
  template: 
    metadata: 
      labels: 
        app: nginx
    spec: 
      containers: 
        - image: nginx-image
          imagePullPolicy: Never
          name: nginx
          ports: 
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https