---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared # 같은 external ip를 사용할 수 있다.
spec:
  # loadBalancerIP: 192.168.2.222
  selector:
    app: phpmyadmin
  ports:
    - name: php-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
        - name: phpmyadmin
          image: phpmyadmin-image
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              name: php-port