---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
      app: ftps
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared # 같은 external ip를 사용할 수 있다.
spec:
  # loadBalancerIP: 192.168.2.222
  selector:
    app: ftps
  ports:
    - name: cmd
      protocol: TCP
      port: 21
      targetPort: 21
    - name: data
      protocol: TCP
      port: 20
      targetPort: 20
    - name: pasv
      protocol: TCP
      port: 10090
      targetPort: 10090
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
        - name: ftps
          image: ftps-image
          imagePullPolicy: Never
          ports:
            - containerPort: 21
              name: cmd
            - containerPort: 20
              name: data
            - containerPort: 10090
              name: pasv
